import type { Metadata } from "next";
import Auth from "../components/auth";


export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Auth />
        {children}
      </body>
    </html>
  );
}
