import type { Metadata } from "next";
import NavBar from "../components/nav-bar";
import Account from "../components/account";

export const metadata: Metadata = {
  title: "Account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="min-h-screen bg-green-200">
        <NavBar />
        <Account />
        {children}
      </body>
    </html>
  );
}
