import type { Metadata } from "next";
import './globals.css'

export const metadata: Metadata = {
  title: "Bulletin Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="min-h-screen bg-green-200">
        {children}
      </body>
    </html>
  );
}
